kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:6.0
    environment:
      ConnectionStrings__DefaultConnection: "Server=db; Port=5432; User Id=main; Password=main; Database=main"
      Jwt__SecretKey: "super secret key"
    commands:
      - sleep 30
      - dotnet run --project targets

  - name: image
    image: plugins/docker
    settings:
      registry: registry.okami101.io
      repo: registry.okami101.io/adr1enbe4udou1n/aspnet-realworld
      tags: latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    depends_on:
      - build

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: front.okami101.io
      port: 2222
      username: okami
      key:
        from_secret: swarm_ssh_key
      script:
        - docker service update --image registry.okami101.io/adr1enbe4udou1n/aspnet-realworld:latest aspnetrealworld_app --with-registry-auth
    depends_on:
      - image

services:
  - name: db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_DATABASE: main

trigger:
  event:
    - push
    - pull_request
