kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:6.0
    environment:
      ConnectionStrings__DefaultConnection: "Server=db; Port=5432; User Id=main; Password=main; Database=main"
    commands:
      - sleep 10 # Wait for PostgreSQL service starting
      - dotnet run --project targets

  - name: image
    image: plugins/docker
    settings:
      registry: registry.okami101.io
      repo: registry.okami101.io/adr1enbe4udou1n/aspnet-core-realworld
      tags: latest
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password

  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: kube_server
      kubernetes_cert:
        from_secret: kube_ca
      kubernetes_token:
        from_secret: kube_token
    commands:
      - kubectl rollout restart deployments/aspnet-core -n conduit

services:
  - name: db
    image: postgres:14
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main

trigger:
  event:
    - push
    - pull_request
