version: "3"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_DATABASE: main
    ports:
      - 3307:3306

  db_test:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: main
      MYSQL_USER: main
      MYSQL_PASSWORD: main
      MYSQL_DATABASE: main
    ports:
      - 3308:3306
