version: "3"
services:
  app:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+
      ConnectionStrings:DefaultConnection: "Server=db; Port=5432; User Id=main; Password=main; Database=main"
      Jwt:SecretKey: "super secret key"
    depends_on:
      - db
    ports:
      - "5000:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
